name: Publish to PyPI
on:
  release:
    - publish


jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution to PyPI
        if: false
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      

